# Generated by Django 4.2.6 on 2023-10-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagem',
        ),
    ]
