# Generated by Django 4.2.6 on 2023-10-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='post_images/'),
        ),
    ]
