# Generated by Django 4.2.6 on 2023-11-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
